name: GitHub Actions Demo
run-name: GitHub Actions Demo push

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: write

    outputs:
      scanfile: ${{ steps.build.outputs.scanfile }}
      status: ${{ steps.scan2.outputs.status }}
      description: ${{ steps.scan2.outputs.description }}

    steps:
      # -------------------------------------
      # we will have to checkout data before we can do anything
      - uses: actions/checkout@v3

      # -------------------------------------
      # build someting
      - name: Build
        id: build
        run: |
          python3 -m pip install --upgrade pip
          pip install hatchling
          python3 -m pip install --upgrade build
          python3 -m build
          echo "scanfile=$( ls dist/*.whl )" >> $GITHUB_OUTPUT

      # -------------------------------------------
      - name: Set pending
        uses: ouzi-dev/commit-status-updater@v2
        with:
          addHoldComment: "true"

      # -------------------------------------
      - name: test composite
        id: scan2
        env:
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
        uses: maarten-boot/rl-scanner-action@v0.1.35
        with:
          artifact-to-scan: ${{ steps.build.outputs.scanfile }}

      - name: verbose3
        run: |
          echo "description: ${{ steps.scan2.outputs.description }}"
          echo "status: ${{ steps.scan2.outputs.status }}"

      - name: Set result status of ReversingLabs/rl-scanner
        if: always()
        uses: ouzi-dev/commit-status-updater@v2
        with:
          addHoldComment: "true"
          description: ${{ steps.scan2.outputs.description }}
          status: ${{ steps.scan2.outputs.status }}
