name: GitHub Actions Demo
run-name: GitHub Actions Demo push

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: write

    outputs:
      status: ${{ steps.output.outputs.status }}
      scanfile: ${{ steps.build.outputs.scanfile }}

    steps:
      # -------------------------------------
      # we will have to checkout data before we can do anything
      - uses: actions/checkout@v3


      # be a but more chatty during testing
      - name: BeVerbose
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"

      # -------------------------------------
      # build someting
      - name: Build
        id: build
        run: |
          python3 -m pip install --upgrade pip
          pip install hatchling
          python3 -m pip install --upgrade build
          python3 -m build
          echo "scanfile=$( ls dist/*.whl )" >>$GITHUB_OUTPUT

      # set the pending status
      - name: Set pending
        uses: ouzi-dev/commit-status-updater@v2
        with:
          addHoldComment: "true"

      # -------------------------------------
      # run the scan action and produce a step_summary
      - name: test composite
        id: scan2
        env:
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
        uses: maarten-boot/rl-scanner-action@v0.1.4
        with:
          my-artifact-to-scan: ${{ steps.build.outputs.scanfile }}

#      # -------------------------------------
#      # run the scan action and produce a step_summary
#      - name: run the reversinglabs/rl-scanner
#        id: scan
#        env:
#          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
#          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
#        uses: maarten-boot/rl-scanner-docker-action@v3.15
#        with:
#          my-artifact-to-scan: ${{ steps.build.outputs.scanfile }}
#
#      # -------------------------------------
#      # upload the rl-scanner report to github
#      # note it is currently not possible to get the url for this asset
#      - name: Archive Report
#        if: success() || failure()
#        uses: actions/upload-artifact@v3
#        with:
#          name: report
#          path: .rl_report
#
#      - name: Set result status of ReversingLabs/rl-scanner
#        if: always()
#        uses: ouzi-dev/commit-status-updater@v2
#        with:
#          addHoldComment: "true"
#          description: ${{ steps.scan.outputs.status }}
#          status: ${{ steps.scan.outputs.state }}
