name: GitHub Actions Demo
run-name: GitHub Actions Demo push
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.output.outputs.status }}
    steps:
      # -------------------------------------
      # we will have to checkout the git before we can scan any item in it
      - name: Check out repository code
        uses: actions/checkout@v3
      # -------------------------------------
      # run the action
      - name: run the reversinglabs/rl-scanner
        id: scan
        env: # Or as an environment variable
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
        uses: maarten-boot/rl-scanner-docker-action@v3.10
        with:
          my-artifact-to-scan: 'README.md'
      # -------------------------------------
      # Use the output from the scan step
      - name: Get the output
        id: output
        if: success() || failure()
        run: |
          echo "The status is: '${{ steps.scan.outputs.status }}'"
          echo "status=${{ steps.scan.outputs.status }}" >>$GITHUB_OUTPUT
      # -------------------------------------
      - name: Archive Report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: .rl_report
