name: GitHub Actions Demo
run-name: GitHub Actions Demo push

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: write

    steps:
      # -------------------------------------
      # we will have to checkout data before we can do anything
      - uses: actions/checkout@v3

      - name: be verbose
        shell: bash
        run: |
          echo "SHA: $GITHUB_SHA"
          echo "REF: $GITHUB_REF"
          echo "REF_NAME: $GITHUB_REF_NAME"
          echo "SHA_SHORT: $( git rev-parse --short HEAD )"
          echo "REPO_NAME: $( basename $(git rev-parse --show-toplevel ) )"

      # -------------------------------------
      # build someting
      - name: Build
        id: build
        shell: bash
        run: |
          python3 -m pip install --upgrade pip
          pip install hatchling
          python3 -m pip install --upgrade build
          python3 -m build
          echo "scanfile=$( ls dist/*.whl )" >> $GITHUB_OUTPUT

      # -------------------------------------
      - name: test composite
        id: scan2
        env:
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
        uses: maarten-boot/rl-scanner-action@v0.1.42
        with:
          artifact-to-scan: ${{ steps.build.outputs.scanfile }}

