name: Release Demo
run-name: Demo release create

on:
  release:
    types: [created]

env:
  DOWNLOAD_PATH: rl-scan-release-assets
  MY_ARTIFACT_TO_SCAN: 'README.md'

jobs:
  ReleaseScanUploadedAssets:
    runs-on: ubuntu-latest
    steps:
      - name: get the latest code
        uses: actions/checkout@v3
        run: git describe --tags --abbrev=0
        run echo ${{ github.event.release.tag_name }}

      # -------------------------------------
      # get the release assets for the current tag
      - name: get any uploaded assets
        id: download
        uses: robinraju/release-downloader@v1.8
        with:
          out-file-path: ${{ env.DOWNLOAD_PATH }}
          tag: ${{ github.event.release.tag_name }}
        run: ls -l
        run: ls -l ${DOWNLOAD_PATH}
        run: echo ${{ fromJson(steps.download.outputs.downloaded_files) }}
        # we may have to tar multiple files together

      # -------------------------------------
      # run the action
      - name: run the reversinglabs/rl-scanner
        id: scan
        env: # Or as an environment variable
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
        uses: maarten-boot/rl-scanner-docker-action@v3.10
        with:
          my-artifact-to-scan: ${{ fromJson(steps.download.outputs.downloaded_files)[0] }}
      # -------------------------------------
      # Use the output from the scan step
      - name: Get the output
        if: success() || failure()
        run: |
          echo "The status is: '${{ steps.scan.outputs.status }}'"
      # -------------------------------------
      - name: Archive Report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: .rl_report
