name: ReversingLabs Rl-Scanner
run-name: ReversingLabs rl-scanner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout-build-scan-action:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: write
      # for sarif upload
      security-events: write
      actions: read
      contents: read
    steps:
      # -------------------------------------
      # we will have to checkout data before we can do anything
      - uses: actions/checkout@v3

      # -------------------------------------
      # build someting, replace this with your build process
      # produces one filename as output in scanfile=<relative file path>
      - name: Build
        id: build
        shell: bash
        run: |
          # prepare the build process
          python3 -m pip install --upgrade pip
          pip install hatchling
          python3 -m pip install --upgrade build
          # make the actual build
          python3 -m build
          # produce a single artifact to scan and set the scanfile output variable
          echo "scanfile=$( ls dist/*.whl )" >> $GITHUB_OUTPUT

      # -------------------------------------
      - name: ReversingLabs apply rl-scanner to the build artifact
        id: rl-scan
        env:
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
        uses: maarten-boot/rl-scanner-action@v0.1.54
        with:
          artifact-to-scan: ${{ steps.build.outputs.scanfile }}
          report-path: "My-Report-Dir"

